[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.12"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.12"

[prune]
  go-tests = true
  unused-packages = true
